### ISSUE TITLE
Blind RSA server key identifiers

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#281]
[Section 6.5 of the issuance protocol](https://www.ietf.org/archive/id/draft-ietf-privacypass-protocol-07.html#section-6.5) diverges from [Section 5.5](https://www.ietf.org/archive/id/draft-ietf-privacypass-protocol-07.html#section-5.5).

In the earlier section:

```
token_key_id = SHA256(concat(0x0001, SerializeElement(pkI)))
```

In the latter, this approximates to:

```
token_key_id = SHA256(DER(SubjectPublicKeyInfo(pkI)))
```

... with no 0x0002.

**Comment by chris-wood** [comment]
I would be fine with adding a token type separator to the type2 variant. It's a simple enough change to make and deploy right now. @tfpauly, @janaiyengar: thoughts?

**Comment by chris-wood** [comment]
We did this for separation between privacy pass and other potential uses of the same key. I don't remember exactly why we didn't do this for type2.

**Comment by tfpauly** [comment]
Had a call, proposing to make things consistent by removing the `concat(0x0001` for Type 1, since it doesn't seem to add any benefit, since the token_input is already binding the protocol to the type and challenge.

Also recommending adding more text (in security considerations) to make it very clear that keys ought to not be reused across protocols.
