### ISSUE TITLE
The challenge doesn't determine what is acceptable

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#303]
Is [this](https://ietf-wg-privacypass.github.io/base-drafts/draft-ietf-privacypass-architecture.html#section-3.1-4) really true?

> The challenge controls the type of token that the Origin will accept for the given resource. 

A challenge is just a declaration from the Origin about what the Client should offer.  It exerts no control.

I would have thought that the arrangement is thus:

* The Origin determines what sorts of token are acceptable, including whether a token is necessary.  This might incorporate any contextual information and so could change between different Clients or over time.
* A valid token includes information that an Origin can use to validate it against its policies.  This includes all the stuff in the list that follows the quoted text (issuance protocol, issuer, redemption context, origin).  Importantly, it does not carry information that directly identifies the Client to any entity other than the Origin; this being the primary privacy benefit to Clients.
* If the Origin determines that a token is necessary it can issue a challenge to the Client.  This challenge might imply that a token that meets these constraints would be acceptable, but see the first point (i.e., the Origin can change its mind).  There should be enough information in the challenge for the Client to obtain a token under reasonable assumptions (the Client understands the request and meets the requirements for token issuance).
* Clients can pre-emptively request token issuance. This might be based on a previous indication that this might work. (I see some caching in the trust tokens API.)

**Comment by chris-wood** [comment]
I'm probably missing the confusion that led to this issue. The arrangement you describe is true, and in that arrangement the only tokens that will be accepted for an Origin are those which verify with a valid challenge. That means the challenge determines how the client produces a valid token. For example, the challenge indicates the token type and therefore the issuance protocol required to produce a token. It also indicates a redemption context and therefore whether or not clients can preemptively request and cache tokens to amortize the cost of issuance. 

I don't think a challenge is _just_ a declaration of what the Client should offer. To me, challenges fundamentally determine the set of possible tokens that clients can produce, and that implies some level of control. 

If "control" is somehow problematic or confusion, perhaps we just phrase this differently. That might be "The challenge determines the set of tokens the Origin will accept for the given resource. This is because tokens cryptographically bind the challenge to a client-chosen nonce."

**Comment by martinthomson** [comment]
As far as I can tell, yes, challenges do constrain what a client can produce in that in order to produce some tokens you need a challenge.  However, the text here might be read to imply that it constrains the server in terms of what it might accept in the future.  So yeah, using "control" is problematic as it too directly implies a link between the signal and the server actions that follow.

I would have said that maybe "A challenge provides the client with the information necessary to obtain tokens that the server might subsequently accept (in this context)."

**Comment by chris-wood** [comment]
That works for me! I'll send a PR.
