### ISSUE TITLE
Bounding Issuer count

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#308]
Should [this](https://ietf-wg-privacypass.github.io/base-drafts/draft-ietf-privacypass-architecture.html#section-5.3-3) be "for each Origin"?

> Clients SHOULD bound the number of Issuers they are willing to request tokens from at any given time. The exact bound depends on the deployment model and number of Clients, i.e., having a very large Client base could potentially allow for larger values. Issuer replacements should only occur with the same frequency as config rotations as they can lead to similar losses in anonymity if clients still hold redemption tokens for previously active Issuers.

The previous paragraph says "For example, these 4 Issuers could be different for each Client."  But doesn't really explain how that might be exploited in an attack on Client privacy.

I think that there is an unstated assumption here: the Client has interactions with multiple Origins and uses a single store of tokens from a limited set of Issuers.  This is not at all clear.  Much of the text of the document concentrates on the challenge-based flow, where an Origin asks the Client to fetch a token from the Issuer.   In that context, this text makes little sense.

It's easy to skip over [this](https://ietf-wg-privacypass.github.io/base-drafts/draft-ietf-privacypass-architecture.html#section-5.3-1):

> If Clients obtain tokens from many Issuers, and Origins later challenge a Client for a token from each Issuer, Origins can learn information about the Client.

That ordering is important.  If you allow there to be a shared store of tokens and Origins can ask "do you have a token from Issuer X?", then this creates shared state that can be queried.  That is a far more dangerous baseline.  For that, there needs to be a global cap on the number of Issuers, or there is some information being released.

On the other hand, I'm not sure that we need the ability to check whether tokens are present.  I think that it is sufficient for the Origin to request a token.  There is value in having a token cache, but caches can operate without necessarily leaking that they are in use.  That doesn't totally eliminate time as a factor, but it might help.

In any case, the document could do a better job of laying out the various expected interaction models up front.  This cached mode is very poorly explained and something of a surprise.

**Comment by chris-wood** [comment]
These are great points. There seem to be two issues here:

1. The privacy implications of "configuration flexibility" (how many Issuers are allowed), and how the number of Issuers should be handled.
2. Interaction models. We really need to add these to the document. Minimally, I think it makes sense to walk through the end-to-end challenge to redemption flow with and without a token cache. We could also cover error cases, e.g., where the Client fails to produce a token and doesn't present anything to the Origin. Failure to produce a token could be due to compatibility reasons, e.g., the challenge token_type, origin_info, or issuer_name values are invalid, or because of attestation or issuance failures.
