### ISSUE TITLE
Privacy: Attester partitioning

### ISSUE THREAD

**Issue by martinthomson** [ietf-wg-privacypass/base-drafts#328]
In a successful issuance exchange, the attester provides the issuer with information about the client.  The text in Section 3.2.1 points out that the way in which information about the client is combined could reduce anonymity set size in ways that affect privacy.

Given that we have a chain of custody, I imagine that the privacy property here is about what the issuer learns about a client.  More information means more information that might then propagate from the issue onward to the origin.  This means that the attester needs to limit what it passes along to only that which is relevant.  The client needs to trust the attester to do this.

... or does it?  The text in Section 3.2.1 implies strongly that this anonymity set size is important, but the constraints on the client-issuer interaction, especially consistency rules, very much limits what the issuer can pass along to the origin.  So maybe the system depends less on trusting the attester and more on the combination of the cryptographic properties of the token and the consistency system that mitigates against misuse.

None of this appears in the privacy considerations.  Should it?

**Comment by martinthomson** [comment]
On this point: "Clients do not explicitly trust Issuers." (Section 3.2.2)  This would invalidate much of the discussion of anonymity sets in attestations.

**Comment by chris-wood** [comment]
There are issuance protocols wherein the issuer learns information about the origin by design, like the [rate-limited issuance protocol](https://ietf-wg-privacypass.github.io/draft-ietf-privacypass-rate-limit-tokens/draft-ietf-privacypass-rate-limit-tokens.html). In this variant, if the attester were to pass information about the client on to the issuer, then the issuer would be able to reconstruct the (client, origin) pair, breaking the unlinkability goals.

I agree that in the case where the issuer learns nothing about the origin in the protocol then reliance on the attester is lessened, but we need to make sure we accommodate future issuance protocols here. I'll think about ways in which we can try to make this more clear. This might go into the privacy considerations, as suggested.
